name: Bug Report
description: Something's wrong!
labels: [ ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Please follow the instructions below.
        In order to remain productive with our time, we will close issues that don't provide enough information.

        If you need help with Hygradle or have a usage question, please reach out in the HytaleModding Discord instead of creating an issue.

        Provide a brief summary of the issue in the title above

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Tell us what happens
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what should happen
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: |
        How has this issue affected you? What are you trying to accomplish?
        Providing context helps us come up with a solution that is most useful in the real world
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Self-contained Reproducer Project
      description: |
        Provide a [minimal, self-contained example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) project demonstrating the problem as a GitHub repository or an attached archive.
    validations:
      required: true

  - type: input
    id: gradle-version
    attributes:
      label: Gradle version
      description: What version of Gradle are you running? Ensure you are using at least the minimum required by your Hygradle version.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Your Environment (optional)
      description: |
        Include as many relevant details about the environment you experienced the bug in
    validations:
      required: false